server:
  port: 3333
  
spring:
  application:
    name: SPRING-API-GATEWAY
  cloud:
    gateway:
      routes:
       
  
      - id: STOCK-CALC-API
        uri: lb://STOCK-CALC-API 
        predicates:
        
        - Path=/api1/**
        
        filters:
        - StripPrefix=1
        

        
        
        
     
        
        
 
       
        
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
    
    
eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    

        
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
        
        
        
            
      
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          