server:
  port: 2222
  
spring:
  application:
    name: STOCK-CALC-API

 
  boot:
    admin:
      client:
        url: http://localhost:8080/
 
eureka:
  instance:
    hostname: localhost
  client:
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      



            

management:
  endpoints:
    web:
      exposure:
        include: '*'