server:
  port: 1212



management:
  endpoints:
    web:
      exposure:
        include:  '*'
       
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080/
  application:
    name: admin-client